github_get_traffic -c gh_traffic/configFiles/Wikipedia-Language-Olga-master_config.ini -o gh_traffic
github_get_traffic -c gh_traffic/configFiles/mlkoblenz_config.ini -o gh_traffic
github_get_traffic -c gh_traffic/configFiles/wiki_history_config.ini -o gh_traffic
github_get_traffic -c gh_traffic/configFiles/promoss_config.ini -o gh_traffic
github_get_traffic -c gh_traffic/configFiles/image-gender-inference_config.ini -o gh_traffic
github_get_traffic -c gh_traffic/configFiles/orc_config.ini -o gh_traffic
github_get_traffic -c gh_traffic/configFiles/Wikipedia-Politician-Network_config.ini -o gh_traffic
github_get_traffic -c gh_traffic/configFiles/jhub_shibboleth_auth_config.ini -o gh_traffic
github_get_traffic -c gh_traffic/configFiles/scientists-analysis-wikipedia_config.ini -o gh_traffic
github_get_traffic -c gh_traffic/configFiles/scientists-analysis_config.ini -o gh_traffic
github_get_traffic -c gh_traffic/configFiles/PythonDataScienceHandbook_config.ini -o gh_traffic
github_get_traffic -c gh_traffic/configFiles/binderhub_config.ini -o gh_traffic
github_get_traffic -c gh_traffic/configFiles/workshop_girls_day_config.ini -o gh_traffic
github_get_traffic -c gh_traffic/configFiles/repo2docker_config.ini -o gh_traffic
github_get_traffic -c gh_traffic/configFiles/ptm_config.ini -o gh_traffic
github_get_traffic -c gh_traffic/configFiles/wiki-download-parse-page-views_config.ini -o gh_traffic
github_get_traffic -c gh_traffic/configFiles/kubespawner_config.ini -o gh_traffic
github_get_traffic -c gh_traffic/configFiles/jupyterhub_config.ini -o gh_traffic
github_get_traffic -c gh_traffic/configFiles/GitHub_traffic_crawler_config.ini -o gh_traffic
github_get_traffic -c gh_traffic/configFiles/introduction_networkx_config.ini -o gh_traffic
github_get_traffic -c gh_traffic/configFiles/wikiwho_interactions_config.ini -o gh_traffic
github_get_traffic -c gh_traffic/configFiles/Homophilic-Ntw-Viz_config.ini -o gh_traffic
github_get_traffic -c gh_traffic/configFiles/flow_config.ini -o gh_traffic
github_get_traffic -c gh_traffic/configFiles/zero-to-jupyterhub-k8s_config.ini -o gh_traffic
github_get_traffic -c gh_traffic/configFiles/Social-Network-Analysis-in-R_config.ini -o gh_traffic
github_get_traffic -c gh_traffic/configFiles/binder-stats_config.ini -o gh_traffic
github_get_traffic -c gh_traffic/configFiles/binder_config.ini -o gh_traffic
github_get_traffic -c gh_traffic/configFiles/vtna_frontend_config.ini -o gh_traffic
