github_get_traffic -c gh_traffic/configFiles/Wikipedia-Language-Olga-master_config.ini -o gh_traffic/Repositories/Wikipedia-Language-Olga-master
github_get_traffic -c gh_traffic/configFiles/mlkoblenz_config.ini -o gh_traffic/Repositories/mlkoblenz
github_get_traffic -c gh_traffic/configFiles/wiki_history_config.ini -o gh_traffic/Repositories/wiki_history
github_get_traffic -c gh_traffic/configFiles/promoss_config.ini -o gh_traffic/Repositories/promoss
github_get_traffic -c gh_traffic/configFiles/image-gender-inference_config.ini -o gh_traffic/Repositories/image-gender-inference
github_get_traffic -c gh_traffic/configFiles/orc_config.ini -o gh_traffic/Repositories/orc
github_get_traffic -c gh_traffic/configFiles/Wikipedia-Politician-Network_config.ini -o gh_traffic/Repositories/Wikipedia-Politician-Network
github_get_traffic -c gh_traffic/configFiles/jhub_shibboleth_auth_config.ini -o gh_traffic/Repositories/jhub_shibboleth_auth
github_get_traffic -c gh_traffic/configFiles/scientists-analysis-wikipedia_config.ini -o gh_traffic/Repositories/scientists-analysis-wikipedia
github_get_traffic -c gh_traffic/configFiles/scientists-analysis_config.ini -o gh_traffic/Repositories/scientists-analysis
github_get_traffic -c gh_traffic/configFiles/PythonDataScienceHandbook_config.ini -o gh_traffic/Repositories/PythonDataScienceHandbook
github_get_traffic -c gh_traffic/configFiles/binderhub_config.ini -o gh_traffic/Repositories/binderhub
github_get_traffic -c gh_traffic/configFiles/workshop_girls_day_config.ini -o gh_traffic/Repositories/workshop_girls_day
github_get_traffic -c gh_traffic/configFiles/repo2docker_config.ini -o gh_traffic/Repositories/repo2docker
github_get_traffic -c gh_traffic/configFiles/ptm_config.ini -o gh_traffic/Repositories/ptm
github_get_traffic -c gh_traffic/configFiles/wiki-download-parse-page-views_config.ini -o gh_traffic/Repositories/wiki-download-parse-page-views
github_get_traffic -c gh_traffic/configFiles/kubespawner_config.ini -o gh_traffic/Repositories/kubespawner
github_get_traffic -c gh_traffic/configFiles/jupyterhub_config.ini -o gh_traffic/Repositories/jupyterhub
github_get_traffic -c gh_traffic/configFiles/Hierarchical_nested_SBM_config.ini -o gh_traffic/Repositories/Hierarchical_nested_SBM
github_get_traffic -c gh_traffic/configFiles/GitHub_traffic_crawler_config.ini -o gh_traffic/Repositories/GitHub_traffic_crawler